### ISSUE TITLE
kamstrup 402/3 on ESPhome

### ISSUE THREAD

**Issue by Dinges28** [matthijsvisser/kamstrup-402-mqtt#10]
Hi Matthijs,

In my search on how to read my kamstrup 403 with an esp32/esphome, I keep on finding your page mentioned by other people..
Because of that, I'm want to ask some help.

I had my Multical 66C working on the esphome configuration  [Proudelm](https://github.com/ProudElm/ESPHome_multical_sensor). But Vattenfall changed the kamstrup now for a 403..
The serial reading of the 403 is significant different than the 66C/602.
My knowledge on C# is little to 0, so I hope you're willing to get me on the road a little.

Your solution requires a connection to an USB cable/port, but my heatingexchanger is too far away from my home automation device, even with long usbcables.... therefore I'm searching for the esphome solution... 

Greetings, Richard

**Comment by christiaangoossens** [comment]
Hi Richard,

I faced the same issue and decided on using a Raspberry Pi Zero W instead (they are in stock right now for less than 20 euros).

It runs a full OS with Python support, so you can run this library as it is.

About the same cost as an ESP, but you have to be lucky with the availability.

**Comment by matthijsvisser** [comment]
Hi,

Have you tried the following project?
https://github.com/cenobitedk/esphome_multical402
