### ISSUE TITLE
Docker error while installing

### ISSUE THREAD

**Issue by 19jm81** [matthijsvisser/kamstrup-402-mqtt#12]
Hi, when I try to install the docker build I get this error:

sudo docker build -t kamstrup .
[+] Building 0.6s (2/2) FINISHED                                                                                                    
 => [internal] load build definition from dockerfile                                                                           0.2s
 => => transferring dockerfile: 2B                                                                                             0.1s
 => [internal] load .dockerignore                                                                                              0.2s
 => => transferring context: 2B                                                                                                0.1s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount863944789/dockerfile: no such file or directory

Any idea how to fix it?

**Comment by matthijsvisser** [comment]
Hey,

Just to make sure that your Docker installatie works, can you run the following commands? 

docker version

and

docker run hello-world

**Comment by 19jm81** [comment]
both commands run fine

**Comment by 19jm81** [comment]
Found it, working now!

**Comment by matthijsvisser** [comment]
Great! What was the issue?

**Comment by 19jm81** [comment]
I edited the docker-compose.yml with the correct locations and that seemed to have helped.
