### ISSUE TITLE
Questions about hardware

### ISSUE THREAD

**Issue by sjoerdos92** [matthijsvisser/kamstrup-402-mqtt#2]
Hi Matthijs @Matthijsvisser, 

I find this project very interesting. I have a Kamstrup 402 and some questions regarding the hardware and other requirements. Can I ask you some questions? 

Are you using this with district heating (stadsverwarming)? 
How difficult is it to place the IR receiver? 
Is IR the only option for communication? 
Which home automation platform are you connecting to? Home assistant, domoticz, other? 
What can you recommend to control the IR receiver? A raspberry pi? 

Thanks!

**Comment by matthijsvisser** [comment]
Hi @sjoerdos92, 

Yes I am using this with district heating. It's not that hard to allign the sensor, but you might need to reposition it a couple of times before getting the first data. For the 402, IR is the only accesable interface as far as I know. I integrated it in Openhab. I can share my configuration if you're interested. I'm using a X86 platform running headless ubuntu to run the code, but any platform running Linux would be fine. Haven't tested it with Windows yet.

**Comment by sjoerdos92** [comment]
Ah great, thanks, your config would be great. I would like to integrate it with homeassistant. I can connect the IR sensor directly to homeassistant or fire up a headless Ubuntu container on my server. Which IR sensor do you use?

**Comment by matthijsvisser** [comment]
The code runs as a separate instance along Openhab, this makes it more flexible and platform independent. Openhab just subscribes on some MQTT topics that is configured in the files below. I use the IR sensor which is linked in the description.

Thing file:
`Bridge mqtt:broker:mqtt_broker "Mqtt broker"
[
	host=<ip>,
	port=<port>,
	secure=<true,false>
]
{
	Thing topic heat_meter "Heat meter" {
		Channels:
			Type number : heat_energy "Warmth consumption"
				[stateTopic="kamstrup/values",
				transformationPattern="JSONPATH:$.energy"]
			Type number : volume "Water consumption"
				[stateTopic="kamstrup/values",
				transformationPattern="JSONPATH:$.volume"]
			Type number : temp1 "Water temperature 1"
				[stateTopic="kamstrup/values",
				transformationPattern="JSONPATH:$.temp1"]
			Type number : temp2 "Water temperature 2"
				[stateTopic="kamstrup/values",
				transformationPattern="JSONPATH:$.temp2"]
}`
Item file:
`Number heat_meter_energy "Warmth consumption [%.3f GJ]" 
	<water_meter> 
	{channel="mqtt:topic:mqtt_broker:heat_meter:heat_energy"}
Number heat_meter_volume "Warm water reading [%.3f m³]" 
	<water_meter> 
	{channel="mqtt:topic:mqtt_broker:heat_meter:volume"}
Number heat_meter_t1 "Input heat [%.2f °C]" 
	<temperaturex> 
	{channel="mqtt:topic:mqtt_broker:heat_meter:temp1"}
Number heat_meter_t2 "Output heat [%.2f °C]" 
	<temperaturex> 
	{channel="mqtt:topic:mqtt_broker:heat_meter:temp2"}
DateTime heat_meter_lastupdate "Last update [%1$td-%1$tm %1$tH:%1$tM]"
	<calendar_schedule>
`
Rule file:
`rule "heat_meter_lastupdate"
when
    Item heat_meter_energy received update
then
    heat_meter_lastupdate.postUpdate(new DateTimeType())
end`

**Comment by sjoerdos92** [comment]
That looks great. I think I'll order such a cable and try it next week. Does your IR instance contain an MQTT broker or does it subscribe to a broker on a separate machine? I'm using some MQTT now but I don't know much about it and about bridging MQTT brokers.

**Comment by Svanberg1** [comment]
Did you get it to work with HomeAssistant?

**Comment by seranoo** [comment]
I did get it to work with HA, finally and not super stable. There is something with the MQTT messaging thing that isn't working properly... It is like it stops listening for the messages after a while...

**Comment by matthijsvisser** [comment]
Ah that's awesome! 

Are you able to pinpoint where the problem resides? Do you still get updates when subscribing to the topic via Mqtt Explorer for example?

Can you maybe share your Home assistant configuration? I'm using Openhab myself, but it could be usefull for others

**Comment by seranoo** [comment]
Hi again,

All works perfect now, not sure what I did wrong in the begining. I messed around with retaining meesages and that didn't work out well. I use Qos = 1 now, not sure if that is good or bad... It works fine and when listenining to the messages in HA it looks like a Qos = 0 message...

Absolutely, I'm happy to share my HA implementation. "fv" (as used in the naming below) = district heating (fjärrvärme in Swedish).

The utility meter in the end give my daily and monthly consumption (https://www.home-assistant.io/integrations/utility_meter/)

My config file for your implementation:

mqtt:
    host: 192.168.1.219
    port: 1883
    client: kamstrup_client3
    topic: homeassistant/sensor/fv
    qos: 1
    retain: False
    authentication: True
    username: xxxx
    password: yyyy
serial_device:
    com_port: /dev/ttyUSB0
kamstrup:
    parameters:
    - energy
    - power
    - flow
    - volume
    - temp1
    - temp2
    poll_interval: 1

--

I use a polling interval of 1 now, but will likely change down the line. However, right now it gives a nice feel of what is happening momentary.

--

For the configuration.yaml in HA:

sensor:
  - platform: mqtt
    name: "fv_energy"
    state_topic: "homeassistant/sensor/fv/values"
    unit_of_measurement: "MWh"
    value_template: "{{ value_json.energy }}"
  - platform: mqtt
    name: "fv_power"
    state_topic: "homeassistant/sensor/fv/values"
    unit_of_measurement: "kW"
    value_template: "{{ value_json.power }}"
  - platform: mqtt
    name: "fv_flow"
    state_topic: "homeassistant/sensor/fv/values"
    unit_of_measurement: "liter"
    value_template: "{{ value_json.flow }}"
  - platform: mqtt
    name: "fv_volume"
    state_topic: "homeassistant/sensor/fv/values"
    unit_of_measurement: "liter"
    value_template: "{{ value_json.volume }}"
  - platform: mqtt
    name: "fv_temp1"
    state_topic: "homeassistant/sensor/fv/values"
    unit_of_measurement: "°C"
    value_template: "{{ value_json.temp1 }}"
  - platform: mqtt
    name: "fv_temp2"
    state_topic: "homeassistant/sensor/fv/values"
    unit_of_measurement: "°C"
    value_template: "{{ value_json.temp2 }}"

utility_meter:
  daily_fv_energy:
    source: sensor.fv_energy
    cycle: daily
  monthly_fv_energy:
    source: sensor.fv_energy
    cycle: monthly 

--

Both sensor and utility meter is to be included in configuration.yaml (or related file).

--

Again, thanks for a great implementation! 

Kind regards,
Magnus
