### ISSUE TITLE
Article covering your repository

### ISSUE THREAD

**Issue by pieterbrink123** [matthijsvisser/kamstrup-402-mqtt#4]
Great project! I just wanted to share that I've written a article that includes your great work. I integrated the readings into the Home Assistant Energy dashboard. It works really well and looks amazing. 

You can find the article here:
https://www.pieterbrinkman.com/2022/02/01/make-your-city-heating-stadsverwarming-smart-and-connect-it-home-assistant-energy-dashboard/

Nogmaals bedankt, heel mooi project!

**Comment by matthijsvisser** [comment]
Hi Pieter,

Great article! Glad that it helped you out. Having those numbers really helped me becoming more aware of my energy consumption. Especially nowadays with the increased energy prices.

Ps: it's MattHijs ;)

**Comment by pieterbrink123** [comment]
Thanks MattHijs :) I've updated your name in the article.
