### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by jeroendew** [matthijsvisser/kamstrup-402-mqtt#8]
Hi Matthijs,

I've have this running perfectly under windows, but since a couple days I have a NAS (synology). 
And I want to move the script to the NAS with docker.  But somehow i'm not able to install this on a docker.

Any change you could help?

Greetings,
Jeroen

**Comment by jrkalf** [comment]
Hi Jeroen,

You can install it in a docker. but it depends on the base operating system you're using. I've been able to run it in a home-assistant add-on form (also a docker container). Just make sure you install the right requirements. As a base I used Alpine Linux.

check my docker file at: https://github.com/jrkalf/kamstrup-40x-mqtt-hassio/

**Comment by jeroendew** [comment]
Hi jrkalf,

Unfortunately the docker version doesn't have the add-on page anymore :-( .
Need to find another way...

**Comment by matthijsvisser** [comment]
Hi,

I'm currently quite busy with work. I might have time at the end of december to imolment it. I noticed that some People forked this repo, you might find your answer there.

Cheers

**Comment by matthijsvisser** [comment]
@jeroendew @jrkalf Just pushed a commit for Docker support
